name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug step - cek apakah secrets terbaca
      - name: Debug secrets
        run: |
          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "Token length: $(echo "${{ secrets.DOCKERHUB_TOKEN }}" | wc -c)"

      # Login ke Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build dan push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: cogan123/hello-devops:latest
