name: CI - Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate version tag
        id: version
        run: |
          VERSION=v1.0.$(date +%s)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            cogan123/hello-devops:latest
            cogan123/hello-devops:${{ env.VERSION }}

      - name: Output version
        run: echo "✅ Image built and pushed with tag ${{ env.VERSION }}"